[versions]
agp = "8.6.1"
documentfile = "1.0.1"
gson = "2.10.1"
kotlin = "2.1.10"
appcompat = "1.7.0"
constraintlayout = "2.2.1"
material = "1.12.0"
junit = "4.13.2"
androidxJunit = "1.1.3"
ext-Junit = "1.1.5"

[libraries]
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx", name = "junit", version.ref = "androidxJunit" }
ext-junit = { group = "ext", name = "junit", version.ref = "ext-junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }